[base]
account = hao1
password = 123456
token = bG1Ma09pNXVuVEFPbFZSb29Bcmp6UWVQcUxmWmh1NHIyMkErcVpZZk1mcmpYMUlBbHY4VnVJdko1R01veVErUGNoNFgxeStGRHN5ZFNGcDA5TlFpSHF0Y2hCRmhCUFAzckEvWENaOEF6bGVabHpOMWhWRDhid21ENEkyT05mYTVpcERoeEtxa3Z1NWpoVHdpdWVTS3dvaUg1QjBTS3dOVEJnZVJDbXdOY2NKSGxzSXU5MW5hWHgxUGtCWnpYVjhiVThYaEpHajRLV3pJNFhqUmxHVjV5RVRQalBOY2xMekN3WkpCb0o0bWxOM001aXR2dGpJUDJPbXVPSHBEblpzQmpzQ2dVVFg4N1ZuLzdEa2gwSzY4YWc9PQ==

[service]
host = ubuntu-180
port = 9990

[map]
scene_id = 2

[business]
rule = 2
areas = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
fixed_store = 

[task]
locations = pp_6b7b5c31, pp_6cfb1f47

[excel]
xlsx_path = ./locations.xlsx
sheet_name = 

[log]
debug = false
log_file = ./region_pickup_to_lift_task.log

[request]
timeout = 15.0
retry_count = 0
retry_delay = 1.0

[areas]
areas = 1,10,11,12,13,14,15,16,17,19,2,20,21,22,23,24,25,26,27,28,3,30,31,32,33,34,35,36,37,38,39,4,40,41,42,43,44,45,46,47,5,6,7,8,9,hoist_L,hoist_R

[logic_mapping]
# 直接定义取放货的配对关系
rule_1 = {"pick": ["pallet_lifter_1", "pallet_lifter_2", "pallet_lifter_3", "pallet_lifter_4","pallet_lifter_5"], "drop": ["packing_stations_1", "packing_stations_2", "packing_stations_3", "packing_stations_4", "packing_stations_5","packing_stations_6", "packing_stations_7", "packing_stations_8", "packing_stations_9"],"hz": 30}
rule_2 = {"pick": ["packing_stations_1", "packing_stations_2", "packing_stations_3", "packing_stations_4", "packing_stations_5","packing_stations_6", "packing_stations_7", "packing_stations_8", "packing_stations_9"], "drop": ["pallet_lifter_1", "pallet_lifter_2", "pallet_lifter_3", "pallet_lifter_4","pallet_lifter_5"],"hz": 6}
rule_3 = {"pick": ["pallet_lifter_1", "pallet_lifter_2", "pallet_lifter_3", "pallet_lifter_4","pallet_lifter_5"], "drop": ["outbound"],"hz": 27}
rule_4 = {"pick": ["inbound"], "drop": ["pallet_lifter_1", "pallet_lifter_2", "pallet_lifter_3", "pallet_lifter_4","pallet_lifter_5"],"hz": 91} 
rule_5 = {"pick": ["packing_stations_1", "packing_stations_2", "packing_stations_3", "packing_stations_4", "packing_stations_5","packing_stations_6", "packing_stations_7", "packing_stations_8", "packing_stations_9"], "drop": ["empty"],"hz": 25} 
rule_6 = {"pick": ["pending_shipment_1", "pending_shipment_2", "pending_shipment_3", "pending_shipment_4", "pending_shipment_5","pending_shipment_6", "pending_shipment_7", "pending_shipment_8", "pending_shipment_9"], "drop": ["outbound"],"hz": 43} 
